In [2]:
import requests
from bs4 import BeautifulSoup
url = 'https://www.bok.or.kr/portal/singl/baseRate/list.do?dataSeCd=01&menuNo=200643'
resp = requests.get(url)
resp

In [3]:
soup = BeautifulSoup(resp.content, 'lxml')
td_tag = soup.select('div table.fixed tr td')
td_tag

[<td class="fb">2020</td>,
 <td>05월 28일</td>,
 <td>0.50</td>,
 <td class="fb">2020</td>,
 <td>03월 17일</td>,
 <td>0.75</td>,
 <td class="fb">2019</td>,
 <td>10월 16일</td>,
 <td>1.25</td>,
 <td class="fb">2019</td>,
 <td>07월 18일</td>,
 <td>1.50</td>,
 <td class="fb">2018</td>,
 <td>11월 30일</td>,
 <td>1.75</td>,
 <td class="fb">2017</td>,
 <td>11월 30일</td>,
 <td>1.50</td>,
 <td class="fb">2016</td>,
 <td>06월 09일</td>,
 <td>1.25</td>,
 <td class="fb">2015</td>,
 <td>06월 11일</td>,
 <td>1.50</td>,
 <td class="fb">2015</td>,
 <td>03월 12일</td>,
 <td>1.75</td>,
 <td class="fb">2014</td>,
 <td>10월 15일</td>,
 <td>2.00</td>,
 <td class="fb">2014</td>,
 <td>08월 14일</td>,
 <td>2.25</td>,
 <td class="fb">2013</td>,
 <td>05월 09일</td>,
 <td>2.50</td>,
 <td class="fb">2012</td>,
 <td>10월 11일</td>,
 <td>2.75</td>,
 <td class="fb">2012</td>,
 <td>07월 12일</td>,
 <td>3.00</td>,
 <td class="fb">2011</td>,
 <td>06월 10일</td>,
 <td>3.25</td>,
 <td class="fb">2011</td>,
 <td>03월 10일</td>,
 <td>3.00</td>,
 <td class="fb">2011</td>,
 <td>01월 13일</td>,
 <td>2.75</td>,
 <td class="fb">2010</td>,
 <td>11월 16일</td>,
 <td>2.50</td>,
 <td class="fb">2010</td>,
 <td>07월 09일</td>,
 <td>2.25</td>,
 <td class="fb">2009</td>,
 <td>02월 12일</td>,
 <td>2.00</td>,
 <td class="fb">2009</td>,
 <td>01월 09일</td>,
 <td>2.50</td>,
 <td class="fb">2008</td>,
 <td>12월 11일</td>,
 <td>3.00</td>,
 <td class="fb">2008</td>,
 <td>11월 07일</td>,
 <td>4.00</td>,
 <td class="fb">2008</td>,
 <td>10월 27일</td>,
 <td>4.25</td>,
 <td class="fb">2008</td>,
 <td>10월 09일</td>,
 <td>5.00</td>,
 <td class="fb">2008</td>,
 <td>08월 07일</td>,
 <td>5.25</td>,
 <td class="fb">2007</td>,
 <td>08월 09일</td>,
 <td>5.00</td>,
 <td class="fb">2007</td>,
 <td>07월 12일</td>,
 <td>4.75</td>,
 <td class="fb">2006</td>,
 <td>08월 10일</td>,
 <td>4.50</td>,
 <td class="fb">2006</td>,
 <td>06월 08일</td>,
 <td>4.25</td>,
 <td class="fb">2006</td>,
 <td>02월 09일</td>,
 <td>4.00</td>,
 <td class="fb">2005</td>,
 <td>12월 08일</td>,
 <td>3.75</td>,
 <td class="fb">2005</td>,
 <td>10월 11일</td>,
 <td>3.50</td>,
 <td class="fb">2004</td>,
 <td>11월 11일</td>,
 <td>3.25</td>,
 <td class="fb">2004</td>,
 <td>08월 12일</td>,
 <td>3.50</td>,
 <td class="fb">2003</td>,
 <td>07월 10일</td>,
 <td>3.75</td>,
 <td class="fb">2003</td>,
 <td>05월 13일</td>,
 <td>4.00</td>,
 <td class="fb">2002</td>,
 <td>05월 07일</td>,
 <td>4.25</td>,
 <td class="fb">2001</td>,
 <td>09월 19일</td>,
 <td>4.00</td>,
 <td class="fb">2001</td>,
 <td>08월 09일</td>,
 <td>4.50</td>,
 <td class="fb">2001</td>,
 <td>07월 05일</td>,
 <td>4.75</td>,
 <td class="fb">2001</td>,
 <td>02월 08일</td>,
 <td>5.00</td>,
 <td class="fb">2000</td>,
 <td>10월 05일</td>,
 <td>5.25</td>,
 <td class="fb">2000</td>,
 <td>02월 10일</td>,
 <td>5.00</td>,
 <td class="fb">1999</td>,
 <td>05월 06일</td>,
 <td>4.75</td>]

###2008년 2월 까지는 콜금리 목표, 2008년 3월부터는 한국은행 기준금리

In [4]:
td_tag_ls = []
for td in td_tag:
    td_tag_ls.append(td.text)
td_tag_ls

['2020',
 '05월 28일',
 '0.50',
 '2020',
 '03월 17일',
 '0.75',
 '2019',
 '10월 16일',
 '1.25',
 '2019',
 '07월 18일',
 '1.50',
 '2018',
 '11월 30일',
 '1.75',
 '2017',
 '11월 30일',
 '1.50',
 '2016',
 '06월 09일',
 '1.25',
 '2015',
 '06월 11일',
 '1.50',
 '2015',
 '03월 12일',
 '1.75',
 '2014',
 '10월 15일',
 '2.00',
 '2014',
 '08월 14일',
 '2.25',
 '2013',
 '05월 09일',
 '2.50',
 '2012',
 '10월 11일',
 '2.75',
 '2012',
 '07월 12일',
 '3.00',
 '2011',
 '06월 10일',
 '3.25',
 '2011',
 '03월 10일',
 '3.00',
 '2011',
 '01월 13일',
 '2.75',
 '2010',
 '11월 16일',
 '2.50',
 '2010',
 '07월 09일',
 '2.25',
 '2009',
 '02월 12일',
 '2.00',
 '2009',
 '01월 09일',
 '2.50',
 '2008',
 '12월 11일',
 '3.00',
 '2008',
 '11월 07일',
 '4.00',
 '2008',
 '10월 27일',
 '4.25',
 '2008',
 '10월 09일',
 '5.00',
 '2008',
 '08월 07일',
 '5.25',
 '2007',
 '08월 09일',
 '5.00',
 '2007',
 '07월 12일',
 '4.75',
 '2006',
 '08월 10일',
 '4.50',
 '2006',
 '06월 08일',
 '4.25',
 '2006',
 '02월 09일',
 '4.00',
 '2005',
 '12월 08일',
 '3.75',
 '2005',
 '10월 11일',
 '3.50',
 '2004',
 '11월 11일',
 '3.25',
 '2004',
 '08월 12일',
 '3.50',
 '2003',
 '07월 10일',
 '3.75',
 '2003',
 '05월 13일',
 '4.00',
 '2002',
 '05월 07일',
 '4.25',
 '2001',
 '09월 19일',
 '4.00',
 '2001',
 '08월 09일',
 '4.50',
 '2001',
 '07월 05일',
 '4.75',
 '2001',
 '02월 08일',
 '5.00',
 '2000',
 '10월 05일',
 '5.25',
 '2000',
 '02월 10일',
 '5.00',
 '1999',
 '05월 06일',
 '4.75']

In [5]:
date_year_ls = []
date_day_ls = []
rate_ls = []
for i in range(0, len(td_tag_ls), 3):
    date_year_ls.append(td_tag_ls[i])
    date_day_ls.append(td_tag_ls[i+ 1])
    rate_ls.append(td_tag_ls[i+ 2])

In [ ]:
len(date_year_ls)

45

In [6]:
import pandas as pd
df = pd.DataFrame({'Date_YY' : date_year_ls, 
                   'Date_MD' : date_day_ls, 
                   'Rate' : rate_ls})
df

   Date_YY  Date_MD  Rate
0     2020  05월 28일  0.50
1     2020  03월 17일  0.75
2     2019  10월 16일  1.25
3     2019  07월 18일  1.50
4     2018  11월 30일  1.75
5     2017  11월 30일  1.50
6     2016  06월 09일  1.25
7     2015  06월 11일  1.50
8     2015  03월 12일  1.75
9     2014  10월 15일  2.00
10    2014  08월 14일  2.25
11    2013  05월 09일  2.50
12    2012  10월 11일  2.75
13    2012  07월 12일  3.00
14    2011  06월 10일  3.25
15    2011  03월 10일  3.00
16    2011  01월 13일  2.75
17    2010  11월 16일  2.50
18    2010  07월 09일  2.25
19    2009  02월 12일  2.00
20    2009  01월 09일  2.50
21    2008  12월 11일  3.00
22    2008  11월 07일  4.00
23    2008  10월 27일  4.25
24    2008  10월 09일  5.00
25    2008  08월 07일  5.25
26    2007  08월 09일  5.00
27    2007  07월 12일  4.75
28    2006  08월 10일  4.50
29    2006  06월 08일  4.25
30    2006  02월 09일  4.00
31    2005  12월 08일  3.75
32    2005  10월 11일  3.50
33    2004  11월 11일  3.25
34    2004  08월 12일  3.50
35    2003  07월 10일  3.75
36    2003  05월 13일  4.00
37    2002  05월 07일  4.25
38    2001  09월 19일  4.00
39    2001  08월 09일  4.50
40    2001  07월 05일  4.75
41    2001  02월 08일  5.00
42    2000  10월 05일  5.25
43    2000  02월 10일  5.00
44    1999  05월 06일  4.75

In [7]:
df = df.drop([44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 0, 1, 2, 3, 4])

In [8]:
df = df.sort_values(by = 'Date_YY', ascending = True, inplace=False, ignore_index=True)

In [ ]:
df

   Date_YY  Date_MD  Rate
0     2004  11월 11일  3.25
1     2005  12월 08일  3.75
2     2005  10월 11일  3.50
3     2006  02월 09일  4.00
4     2006  06월 08일  4.25
5     2006  08월 10일  4.50
6     2007  07월 12일  4.75
7     2007  08월 09일  5.00
8     2008  08월 07일  5.25
9     2008  10월 09일  5.00
10    2008  10월 27일  4.25
11    2008  11월 07일  4.00
12    2008  12월 11일  3.00
13    2009  01월 09일  2.50
14    2009  02월 12일  2.00
15    2010  11월 16일  2.50
16    2010  07월 09일  2.25
17    2011  01월 13일  2.75
18    2011  03월 10일  3.00
19    2011  06월 10일  3.25
20    2012  07월 12일  3.00
21    2012  10월 11일  2.75
22    2013  05월 09일  2.50
23    2014  08월 14일  2.25
24    2014  10월 15일  2.00
25    2015  03월 12일  1.75
26    2015  06월 11일  1.50
27    2016  06월 09일  1.25
28    2017  11월 30일  1.50

In [9]:
li = []
for i in range(len(df['Date_MD'])):
    li.append(df['Date_MD'][i].replace('월', '.').replace('일', '').replace(' ', ''))
li

['11.11',
 '12.08',
 '10.11',
 '02.09',
 '06.08',
 '08.10',
 '07.12',
 '08.09',
 '08.07',
 '10.09',
 '10.27',
 '11.07',
 '12.11',
 '01.09',
 '02.12',
 '11.16',
 '07.09',
 '01.13',
 '03.10',
 '06.10',
 '07.12',
 '10.11',
 '05.09',
 '08.14',
 '10.15',
 '03.12',
 '06.11',
 '06.09',
 '11.30']

In [10]:
a = df['Date_YY'] + '.' + li

In [11]:
df.insert(loc=0, column='Date', value=pd.to_datetime(a, format='%Y-%m-%d'))

In [12]:
df_all = df
df_all

         Date Date_YY  Date_MD  Rate
0  2004-11-11    2004  11월 11일  3.25
1  2005-12-08    2005  12월 08일  3.75
2  2005-10-11    2005  10월 11일  3.50
3  2006-02-09    2006  02월 09일  4.00
4  2006-06-08    2006  06월 08일  4.25
5  2006-08-10    2006  08월 10일  4.50
6  2007-07-12    2007  07월 12일  4.75
7  2007-08-09    2007  08월 09일  5.00
8  2008-08-07    2008  08월 07일  5.25
9  2008-10-09    2008  10월 09일  5.00
10 2008-10-27    2008  10월 27일  4.25
11 2008-11-07    2008  11월 07일  4.00
12 2008-12-11    2008  12월 11일  3.00
13 2009-01-09    2009  01월 09일  2.50
14 2009-02-12    2009  02월 12일  2.00
15 2010-11-16    2010  11월 16일  2.50
16 2010-07-09    2010  07월 09일  2.25
17 2011-01-13    2011  01월 13일  2.75
18 2011-03-10    2011  03월 10일  3.00
19 2011-06-10    2011  06월 10일  3.25
20 2012-07-12    2012  07월 12일  3.00
21 2012-10-11    2012  10월 11일  2.75
22 2013-05-09    2013  05월 09일  2.50
23 2014-08-14    2014  08월 14일  2.25
24 2014-10-15    2014  10월 15일  2.00
25 2015-03-12    2015  03월 12일  1.75
26 2015-06-11    2015  06월 11일  1.50
27 2016-06-09    2016  06월 09일  1.25
28 2017-11-30    2017  11월 30일  1.50

In [13]:
del df['Date_MD'], df['Date_YY']

In [ ]:
#############################
### 12	2008-10-09	5.00 ####
### 16	2010-07-09	2.25 ####
### 19	2011-03-10	3.00 ####
###### 일단 제거해줌 ########
#############################

In [14]:
df.to_csv('한국은행 기준금리_origin.csv', index=False)

In [15]:
df_rate = pd.read_csv('한국은행 기준금리_origin.csv')
df_rate

          Date  Rate
0   2004-11-11  3.25
1   2005-12-08  3.75
2   2005-10-11  3.50
3   2006-02-09  4.00
4   2006-06-08  4.25
5   2006-08-10  4.50
6   2007-07-12  4.75
7   2007-08-09  5.00
8   2008-08-07  5.25
9   2008-10-09  5.00
10  2008-10-27  4.25
11  2008-11-07  4.00
12  2008-12-11  3.00
13  2009-01-09  2.50
14  2009-02-12  2.00
15  2010-11-16  2.50
16  2010-07-09  2.25
17  2011-01-13  2.75
18  2011-03-10  3.00
19  2011-06-10  3.25
20  2012-07-12  3.00
21  2012-10-11  2.75
22  2013-05-09  2.50
23  2014-08-14  2.25
24  2014-10-15  2.00
25  2015-03-12  1.75
26  2015-06-11  1.50
27  2016-06-09  1.25
28  2017-11-30  1.50

## jy_ 2005.01.01 ~ 2005.12.07 rate 3.25로 채워주기

In [ ]:
type(df_rate['Date'][0])

str

In [16]:
df['Date'] = pd.to_datetime(df['Date'])

In [17]:
type(df['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [18]:
df_rate = df_rate.sort_values(by='Date', ascending=False, ignore_index=True)

In [19]:
df_rate

          Date  Rate
0   2017-11-30  1.50
1   2016-06-09  1.25
2   2015-06-11  1.50
3   2015-03-12  1.75
4   2014-10-15  2.00
5   2014-08-14  2.25
6   2013-05-09  2.50
7   2012-10-11  2.75
8   2012-07-12  3.00
9   2011-06-10  3.25
10  2011-03-10  3.00
11  2011-01-13  2.75
12  2010-11-16  2.50
13  2010-07-09  2.25
14  2009-02-12  2.00
15  2009-01-09  2.50
16  2008-12-11  3.00
17  2008-11-07  4.00
18  2008-10-27  4.25
19  2008-10-09  5.00
20  2008-08-07  5.25
21  2007-08-09  5.00
22  2007-07-12  4.75
23  2006-08-10  4.50
24  2006-06-08  4.25
25  2006-02-09  4.00
26  2005-12-08  3.75
27  2005-10-11  3.50
28  2004-11-11  3.25

In [20]:
import numpy as np
df_rate_arr = np.array(df_rate[['Date','Rate']])

In [21]:
df_rate_arr

array([['2017-11-30', 1.5],
       ['2016-06-09', 1.25],
       ['2015-06-11', 1.5],
       ['2015-03-12', 1.75],
       ['2014-10-15', 2.0],
       ['2014-08-14', 2.25],
       ['2013-05-09', 2.5],
       ['2012-10-11', 2.75],
       ['2012-07-12', 3.0],
       ['2011-06-10', 3.25],
       ['2011-03-10', 3.0],
       ['2011-01-13', 2.75],
       ['2010-11-16', 2.5],
       ['2010-07-09', 2.25],
       ['2009-02-12', 2.0],
       ['2009-01-09', 2.5],
       ['2008-12-11', 3.0],
       ['2008-11-07', 4.0],
       ['2008-10-27', 4.25],
       ['2008-10-09', 5.0],
       ['2008-08-07', 5.25],
       ['2007-08-09', 5.0],
       ['2007-07-12', 4.75],
       ['2006-08-10', 4.5],
       ['2006-06-08', 4.25],
       ['2006-02-09', 4.0],
       ['2005-12-08', 3.75],
       ['2005-10-11', 3.5],
       ['2004-11-11', 3.25]], dtype=object)

In [22]:
import datetime

datetime.date(2005,12,7) - datetime.date(2005,1,1)

datetime.timedelta(340)

In [ ]:
datetime.date(2005,1,1) + datetime.timedelta(+340)

datetime.date(2005, 12, 7)

In [23]:
rate_list = []

for term in range(0,341,1):
    Date = str((datetime.date(2005,1,1) + datetime.timedelta(+term)).strftime('%Y-%m-%d'))
    rate = '3.25'
    tmp = (Date,rate)
    rate_list.append(tmp)

In [24]:
rate_list[0]

('2005-01-01', '3.25')

In [25]:
new_rate = pd.DataFrame(rate_list, columns=['Date','Rate'])
new_rate

           Date  Rate
0    2005-01-01  3.25
1    2005-01-02  3.25
2    2005-01-03  3.25
3    2005-01-04  3.25
4    2005-01-05  3.25
..          ...   ...
336  2005-12-03  3.25
337  2005-12-04  3.25
338  2005-12-05  3.25
339  2005-12-06  3.25
340  2005-12-07  3.25

[341 rows x 2 columns]

In [26]:
new_rate['Date'] = pd.to_datetime(new_rate['Date'])

In [27]:
type(new_rate['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [28]:
df_rate.Date.astype(str)

0     2017-11-30
1     2016-06-09
2     2015-06-11
3     2015-03-12
4     2014-10-15
5     2014-08-14
6     2013-05-09
7     2012-10-11
8     2012-07-12
9     2011-06-10
10    2011-03-10
11    2011-01-13
12    2010-11-16
13    2010-07-09
14    2009-02-12
15    2009-01-09
16    2008-12-11
17    2008-11-07
18    2008-10-27
19    2008-10-09
20    2008-08-07
21    2007-08-09
22    2007-07-12
23    2006-08-10
24    2006-06-08
25    2006-02-09
26    2005-12-08
27    2005-10-11
28    2004-11-11
Name: Date, dtype: object

In [29]:
new_rate.Date = new_rate.Date.astype(str)

In [30]:
new_rate.Date

0      2005-01-01
1      2005-01-02
2      2005-01-03
3      2005-01-04
4      2005-01-05
          ...
336    2005-12-03
337    2005-12-04
338    2005-12-05
339    2005-12-06
340    2005-12-07
Name: Date, Length: 341, dtype: object

In [31]:
new_rate_df = pd.concat([df_rate, new_rate], axis=0)
new_rate_df

           Date  Rate
0    2017-11-30   1.5
1    2016-06-09  1.25
2    2015-06-11   1.5
3    2015-03-12  1.75
4    2014-10-15     2
..          ...   ...
336  2005-12-03  3.25
337  2005-12-04  3.25
338  2005-12-05  3.25
339  2005-12-06  3.25
340  2005-12-07  3.25

[370 rows x 2 columns]

In [32]:
new_rate_df = new_rate_df.sort_values(by='Date', ascending=False, ignore_index=True)

In [33]:
new_rate_df

           Date  Rate
0    2017-11-30   1.5
1    2016-06-09  1.25
2    2015-06-11   1.5
3    2015-03-12  1.75
4    2014-10-15     2
..          ...   ...
365  2005-01-04  3.25
366  2005-01-03  3.25
367  2005-01-02  3.25
368  2005-01-01  3.25
369  2004-11-11  3.25

[370 rows x 2 columns]

### jy_수정 부분 끗

In [ ]:
date_2005 = pd.date_range('2005-01-01', periods=31+28+31+30+31+30+31+31+30+31+30+7)
date_2005

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10',
               ...
               '2005-11-28', '2005-11-29', '2005-11-30', '2005-12-01',
               '2005-12-02', '2005-12-03', '2005-12-04', '2005-12-05',
               '2005-12-06', '2005-12-07'],
              dtype='datetime64[ns]', length=341, freq='D')

In [ ]:
missing_2005 = pd.Series(range(len(date_2005)), index=date_idx)
missing_2005

2005-01-01      0
2005-01-02      1
2005-01-03      2
2005-01-04      3
2005-01-05      4
             ...
2005-12-03    336
2005-12-04    337
2005-12-05    338
2005-12-06    339
2005-12-07    340
Freq: D, Length: 341, dtype: int64

In [ ]:
freq_2005 = missing_2005.resample('D')
freq_2005.first()

2005-01-01      0
2005-01-02      1
2005-01-03      2
2005-01-04      3
2005-01-05      4
             ...
2005-12-03    336
2005-12-04    337
2005-12-05    338
2005-12-06    339
2005-12-07    340
Freq: D, Length: 341, dtype: int64

In [ ]:
type(missing_2005)

pandas.core.series.Series

In [ ]:
df_rate['Date'].append(date_2005, ignore_index=True)

TypeError: ignored

In [ ]:
df_rate['Date']

0     2004-11-11
1     2005-12-08
2     2005-10-11
3     2006-02-09
4     2006-06-08
5     2006-08-10
6     2007-07-12
7     2007-08-09
8     2008-08-07
9     2008-10-09
10    2008-10-27
11    2008-11-07
12    2008-12-11
13    2009-01-09
14    2009-02-12
15    2010-11-16
16    2010-07-09
17    2011-01-13
18    2011-03-10
19    2011-06-10
20    2012-07-12
21    2012-10-11
22    2013-05-09
23    2014-08-14
24    2014-10-15
25    2015-03-12
26    2015-06-11
27    2016-06-09
28    2017-11-30
Name: Date, dtype: object